### ISSUE TITLE
TypeError: can only concatenate str (not "bytes") to str

### ISSUE THREAD

**Issue by KittoniuM** [SirTangent/VOXGen#1]
C:\Users\Elite130\Desktop\VOXGen-master>python VOXGen.py  "hello this"
['hello', 'this']
['hello', 'this']
Traceback (most recent call last):
  File "VOXGen.py", line 42, in <module>
    splice = splice + (sound.readframes(sound.getnframes()))
TypeError: can only concatenate str (not "bytes") to str

**Comment by nicoskiy** [comment]
Go into VOXGen.py and replace line 33 with this
splice =b""
Good as new

**Comment by nicoskiy** [comment]
Also, make sure you delete the out.wav file if you want to make another one (Or you'll get an error)
